name: "Main"

on: # yamllint disable-line rule:truthy
  pull_request: null
  push:
    branches:
      - "main"

env:
  DEFAULT_PHP_VERSION: "8.2"
  RUN_ENVIRONMENT: "local"

jobs:
  tests:
    name : Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.2'
          - '8.3'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php }}"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "locked"

      - name: "Run unit tests"
        run: "make test-unit ENV=${{ env.RUN_ENVIRONMENT }}"

  quality:
    name: Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ env.DEFAULT_PHP_VERSION }}"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "locked"

      - name: "CGL"
        run: "make code-style ENV=${{ env.RUN_ENVIRONMENT }}"